# Use Binance Testnet if set to true; set to false for live trading
testnet: true

# List of bots with their respective configurations
bots:
  - symbol: BTCUSDT
    no_of_decimal_places: 1
    volume: 0.01
    proportion: 0.04
    take_profit_percent: 5
    num_of_grids: 10
    leverage: 10
  - symbol: ETHUSDT
    no_of_decimal_places: 2
    volume: 0.01
    proportion: 0.04
    take_profit_percent: 5
    num_of_grids: 10
    leverage: 10
